### PR TITLE
Update main.js

### PR DESCRIPTION
**Pull request by ouun**

### CODE REVIEW

**Comment by ouun** [comment]
@aristath Sorry for opening that many PRs. Should be all together in one... 
The 4 PRs allow resetting the select field to their default value.

**Comment by aristath** [comment]
I combined them all in 1 (see https://github.com/kirki-framework/control-react-select/pull/5) and merged.
I also whitelisted the `isClearable` property in the object, so this can now be disabled on a per-control basis by adding `'isClearable' => false` to the control in PHP 👍

**Comment by aristath** [comment]
I also changed the value on clear. Clear should be empty, not the default value. I think it makes more sense that way...

**Comment by aristath** [comment]
Another update: For backwards-compatibility purposes, `isClearable` is now opt-in, so if you want that on your controls it will have to set to true on a per-control basis.

**Comment by ouun** [comment]
Excellent, thank you! I just disagree that it should be cleared to an empty value. At the end I can set an empty value as the default, so this is the case if nothing specific is set anyways. Bu if I have a predefined colour and the user overwrites it, he should be able to reset it to whatever default is set.
At least it would require an option for that. Don’t you agree?

**Comment by aristath** [comment]
`select` should show the selected value, and if it's empty then the selected value should be empty.

`clear` empties the selection, therefore it makes sense to me that the value returned should be clear. If on `clear` it was resetting the select to the default option in the UI instead of emptying the selection I'd agree with you. But that wouldn't math the concept of the `x` button...

Overriding colors is one use-case.
But there's lots of other use-cases. In typography fields for example if I clear the selection it's because I don't want a font-family to be selected. When the select field is empty I expect there to be nothing selected. Otherwise the select field shows empty, but the value selected is `Roboto` (if that's my default). It's inconsistent, the UI doesn't show the truth.
Now if we added a `resetToDefault` component with a 🔄 icon instead ox `x` then I'd agree. And that's a great feature to add btw, but it has to be separate from `isClearable`. Clearable and resetable are different concepts.

**Comment by ouun** [comment]
@aristath as I stumble over this again, while setting up a typography font-family control: 
How would it be to allow `isClearable` to be either a boolean (true/false) which clears it as described by your OR a string (e.g. "Roboto") to reset to a defined value.
We could even use different icons for this and it does not need an additional setting.

**Pull request merged**
